name: Sync Upstream and Fork

on:
  workflow_dispatch:  # Permet un déclenchement manuel

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream (repo père)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

     

      - name: Add remotes
        run: |
          git remote add fork https://github.com/LaSyCa/Project_Countries.git
          git fetch fork

      - name: Merge fork into upstream (repo père)
        run: |
          git checkout main
          git merge fork/main --no-edit
          git push origin main  # Pousse dans le repo père

